# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request CI - NextJS & Hardhat

on:
  workflow_dispatch:
  push:
    branches: [production, release, next]
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          # for has changed path
          fetch-depth: 5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --immutable

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-contracts
        with:
          paths: packages/contracts .github/workflows

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-sdk
        with:
          paths: packages/sdk-js .github/workflows

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-app
        with:
          paths: packages/app .github/workflows

      - name: 'changed paths'
        env:
          CHANGED_APP: ${{ steps.changed-app.outputs.changed == 'true' }}
          CHANGED_CONTRACTS: ${{ steps.changed-contracts.outputs.changed == 'true' }}
          CHANGED_SDK: ${{ steps.changed-sdk.outputs.changed == 'true' }}
        run: |
          echo "$CHANGED_APP $CHANGED_CONTRACTS $CHANGED_SDK"

      - name: 'Test Build'
        run: |
          yarn build

      - name: 'setup test contracts for sdk'
        if: ${{ steps.changed-contracts.outputs.changed == 'true' || steps.changed-sdk.outputs.changed == 'true' }}
        run: |
          yarn test:setup

      - name: 'test sdk & contracts'
        if: ${{ steps.changed-contracts.outputs.changed == 'true' || steps.changed-sdk.outputs.changed == 'true' }}
        run: |
          yarn test
